1. Импорт библиотеки NumPy

In [1]:
import numpy as np

2. Примеры создания массивов

In [2]:
# из обычных списков
print(np.array((1, 2, 3, 4 ,5))) # одномерный
a = np.array([
    [0.1, 0.2, 0.3, 0.4, 0.5],
    [0.6, 0.7, 0.8, 0.9, 1.0]
])  # двумерный
print(a)
b = np.array(([[[1, 2 ,3], [4, 5, 6], [7, 8, 9]], [[9, 8, 7], [6, 5, 4], [3, 2, 1]]])) # трёхмерный
print(b)

# с использованием функций
print(np.zeros((5, 5))) # двумерная матрица из нулей
print(np.ones((2, 2, 3))) # трёхмерная матрица из единиц
print(np.arange(1, 2, 0.1)) # матрица из 10 элементов с шагом 0.1
print(np.eye(3)) # единичная матрица
print(np.empty((2, 3))) # пустая матрица (с мусором из памяти)

[1 2 3 4 5]
[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


3. Демонстрация атрибутов

In [3]:
print(a.shape) # форма матрицы
print(a.dtype) # тип данных матрицы
print(b.shape)
print(b.dtype)

(2, 5)
float64
(2, 3, 3)
int64


4. Примеры индексирования и срезов

In [4]:
print(a[0]) # первая строка матрицы 'a'
print(a[1][-1]) # последний элемент второй строки
print(a[0][1:4]) # элементы первой строки со 2 по 4
print(a[[0, 1], [0, 1]]) # 1 строка 1 столбец, 2 строка 2 столбец (диагональ)
print(b[1][2]) # третья строка второй матрицы 'b'
print(b[0][:2]) # первые две строки первой матрицы
print(b[1][[0, 1]]) # первая и вторая строки второй матрицы

[0.1 0.2 0.3 0.4 0.5]
1.0
[0.2 0.3 0.4]
[0.1 0.7]
[3 2 1]
[[1 2 3]
 [4 5 6]]
[[9 8 7]
 [6 5 4]]


5. Примеры векторных операций и базовых статистик

In [5]:
x = np.array([1, 2, 3 ,4])
y = np.array([5, 6, 7, 8])
print(x + y) # сложение
print(x - y) # вычитание
print(x - 10)
print(y * 8)
print(x * y)
print(np.array([1, 2, 3, 4]) * np.array([[1], [2], [3], [4]])) # умножение строки на столбец
print(np.mean(x)) # среднее арифметическое
print(np.min(y)) # минимальное значение
print(np.max(y)) # максимальное значение

[ 6  8 10 12]
[-4 -4 -4 -4]
[-9 -8 -7 -6]
[40 48 56 64]
[ 5 12 21 32]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
2.5
5
8
